-- basic
require("user.options")
require("user.plugins")
require("user.keymap")
require('impatient')

-- plugins settings
require("user.alpha")
require("user.autopairs")
require("user.bufferline")
require("user.colorscheme")
require("user.cursorline")
require("user.gitsigns")
require("user.indent_blankline")
require("user.lsp")
require("user.lualine")
require("user.nvim_tree")
require("user.project")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
require("user.whichkey")
