require("snacks").setup({
	lazygit = { enabled = true },
	terminal = { enabled = true },
	toggle = { enabled = true },
	-- bigfile = { enabled = true },
	-- bufdelete = { enabled = false },
	-- dashboard = { enabled = false },
	-- explorer = { enabled = false },
	-- indent = {
	-- 	enabled = true,
	-- 	scope = { enabled = false },
	-- },
	-- input = { enabled = false },
	-- notifier = { enabled = false },
	-- quickfile = { enabled = true },
	-- scope = { enabled = false },
	-- scroll = { enabled = false },
	-- scratch = { enabled = true },
	-- statuscolumn = { enabled = false },
	-- words = { enabled = false },
	-- zen = { enabled = false },
})
