require("mini.extra").setup()

vim.keymap.set("n", "<leader>s/b", function()
	MiniExtra.pickers.buf_lines({ scope = "all" })
end, { desc = "Grep Open Buffers" })
vim.keymap.set("n", "<leader>fg", MiniExtra.pickers.git_files, { desc = "Find Git Files" })
vim.keymap.set("n", "<leader>sgd", function()
	MiniExtra.pickers.git_hunks({ scope = "unstaged" })
end, { desc = "Git Diffs" })
vim.keymap.set("n", "<leader>sd", MiniExtra.pickers.diagnostic, { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>shc", function()
	MiniExtra.pickers.history({ scope = ":" })
end, { desc = "Command History" })
vim.keymap.set("n", "<leader>shs", function()
	MiniExtra.pickers.history({ scope = "/" })
end, { desc = "Search History" })
vim.keymap.set("n", "<leader>sj", function()
	MiniExtra.pickers.list({ scope = "jump" })
end, { desc = "Jumps" })
vim.keymap.set("n", "<leader>sl", function()
	MiniExtra.pickers.buf_lines({ scope = "all" })
end, { desc = "Lines" })
vim.keymap.set("n", "<leader>sm", MiniExtra.pickers.marks, { desc = "Marks" })
vim.keymap.set("n", "<leader>sM", MiniExtra.pickers.manpages, { desc = "Man Pages" })
vim.keymap.set("n", "<leader>sq", function()
	MiniExtra.pickers.list({ scope = "quickfix" })
end, { desc = "Quickfix" })
vim.keymap.set("n", "<leader>sr", MiniExtra.pickers.registers, { desc = "Register" })
vim.keymap.set("n", "<leader>cr", function()
	MiniExtra.pickers.lsp({ scope = "references" })
end, { desc = "References" })
vim.keymap.set("n", "<leader>cd", function()
	MiniExtra.pickers.lsp({ scope = "definition" })
end, { desc = "Definitions" })
vim.keymap.set("n", "<leader>cD", function()
	MiniExtra.pickers.lsp({ scope = "declaration" })
end, { desc = "Declaration" })
vim.keymap.set("n", "<leader>cI", function()
	MiniExtra.pickers.lsp({ scope = "implementation" })
end, { desc = "Implementation" })
vim.keymap.set("n", "<leader>ct", function()
	MiniExtra.pickers.lsp({ scope = "type_definition" })
end, { desc = "Type Definition" })
vim.keymap.set("n", "<leader>cs", function()
	MiniExtra.pickers.lsp({ scope = "document_symbol" })
end, { desc = "Symbols" })
vim.keymap.set("n", "<leader>cS", function()
	MiniExtra.pickers.lsp({ scope = "workspace_symbol_live" })
end, { desc = "Workspace Symbols" })
