vim.keymap.set("n", "<leader><space>", "<cmd>lua Snacks.picker.smart()<cr>", { desc = "Smart Search" })
vim.keymap.set("n", "<leader>,", "<cmd>lua Snacks.picker.buffers()<cr>", { desc = "Buffers" })
vim.keymap.set("n", "<leader>/", "<cmd>lua Snacks.picker.grep()<cr>", { desc = "Grep" })
vim.keymap.set("n", "<leader>p", "<cmd>lua Snacks.picker.pickers()<cr>", { desc = "Pickers" })
vim.keymap.set("n", "<leader><tab>", "<cmd>lua Snacks.picker.resume()<cr>", { desc = "Pickers Resume" })

vim.keymap.set("n", "<leader>bd", "<cmd>lua Snacks.bufdelete.delete()<cr>", { desc = "Close Current Buffer" })
vim.keymap.set("n", "<leader>bo", "<cmd>lua Snacks.bufdelete.other()<cr>", { desc = "Close Other Buffers" })
vim.keymap.set("n", "<leader>b.", "<cmd>lua Snacks.scratch()<cr>", { desc = "Toggle Scratch Buffer" })
vim.keymap.set("n", "<leader>bs", "<cmd>lua Snacks.scratch.select()<cr>", { desc = "Select Scratch Buffer" })

vim.keymap.set("n", "<leader>gg", "<cmd>lua Snacks.lazygit()<cr>", { desc = "Lazygit" })
vim.keymap.set("n", "<leader>ut", "<cmd>lua Snacks.terminal()<cr>", { desc = "Terminal" })

vim.keymap.set(
	"n",
	"<leader>fc",
	"<cmd>lua Snacks.picker.files({cwd=vim.fn.stdpath('config')})<cr>",
	{ desc = "Find Config File" }
)
vim.keymap.set("n", "<leader>ff", "<cmd>lua Snacks.picker.files()<cr>", { desc = "Find Files" })
vim.keymap.set("n", "<leader>fd", "<cmd>lua Snacks.picker.git_status()<cr>", { desc = "Git Status Files" })
vim.keymap.set("n", "<leader>fg", "<cmd>lua Snacks.picker.git_files()<cr>", { desc = "Find Git Files" })
vim.keymap.set("n", "<leader>fp", "<cmd>lua Snacks.picker.projects()<cr>", { desc = "Projects" })

vim.keymap.set("n", "<leader>s/b", "<cmd>lua Snacks.picker.grep_buffers()<cr>", { desc = "Grep Open Buffers" })
vim.keymap.set("n", "<leader>s/w", "<cmd>lua Snacks.picker.grep_word()<cr>", { desc = "Grep Word" })
vim.keymap.set("n", "<leader>sgs", "<cmd>lua Snacks.picker.git_status()<cr>", { desc = "Git Status" })
vim.keymap.set("n", "<leader>sgd", "<cmd>lua Snacks.picker.git_diff()<cr>", { desc = "Git Diffs" })
vim.keymap.set("n", "<leader>sd", "<cmd>lua Snacks.picker.diagnostics()<cr>", { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>shc", "<cmd>lua Snacks.picker.command_history()<cr>", { desc = "Command History" })
vim.keymap.set("n", "<leader>shs", "<cmd>lua Snacks.picker.search_history()<cr>", { desc = "Search History" })
vim.keymap.set("n", "<leader>shn", "<cmd>lua Snacks.picker.notifications()<cr>", { desc = "Show Notifier History" })
vim.keymap.set("n", "<leader>sH", "<cmd>lua Snacks.picker.help()<cr>", { desc = "Help" })
vim.keymap.set("n", "<leader>sj", "<cmd>lua Snacks.picker.jumps()<cr>", { desc = "Jumps" })
vim.keymap.set("n", "<leader>sl", "<cmd>lua Snacks.picker.lines()<cr>", { desc = "Lines" })
vim.keymap.set("n", "<leader>sm", "<cmd>lua Snacks.picker.marks()<cr>", { desc = "Marks" })
vim.keymap.set("n", "<leader>sM", "<cmd>lua Snacks.picker.man()<cr>", { desc = "Man Pages" })
vim.keymap.set("n", "<leader>sq", "<cmd>lua Snacks.picker.qflist()<cr>", { desc = "Quickfix" })
vim.keymap.set("n", "<leader>sr", "<cmd>lua Snacks.picker.registers()<cr>", { desc = "Register" })
vim.keymap.set("n", "<leader>su", "<cmd>lua Snacks.picker.undo()<cr>", { desc = "Undo History" })
vim.keymap.set("n", "<leader>cr", "<cmd>lua Snacks.picker.lsp_references()<cr>", { desc = "References" })
vim.keymap.set("n", "<leader>cd", "<cmd>lua Snacks.picker.lsp_definitions()<cr>", { desc = "Definitions" })
vim.keymap.set("n", "<leader>cD", "<cmd>lua Snacks.picker.lsp_declarations()<cr>", { desc = "Declaration" })
vim.keymap.set("n", "<leader>cI", "<cmd>lua Snacks.picker.lsp_implementations()<cr>", { desc = "Implementation" })
vim.keymap.set("n", "<leader>ct", "<cmd>lua Snacks.picker.lsp_type_definitions()<cr>", { desc = "Type Definition" })
vim.keymap.set("n", "<leader>ci", "<cmd>lua Snacks.picker.lsp_incoming_calls()<cr>", { desc = "Calls Incoming" })
vim.keymap.set("n", "<leader>co", "<cmd>lua Snacks.picker.lsp_outgoing_calls()<cr>", { desc = "Calls Outgoing" })
vim.keymap.set("n", "<leader>cn", "<cmd>lua Snacks.rename.rename_file()<cr>", { desc = "Rename File" })
vim.keymap.set("n", "<leader>cs", "<cmd>lua Snacks.picker.lsp_symbols()<cr>", { desc = "Symbols" })
vim.keymap.set("n", "<leader>cS", "<cmd>lua Snacks.picker.lsp_workspace_symbols()<cr>", { desc = "Workspace Symbols" })
